# Use the official OpenJDK image as the base image
FROM eclipse-temurin:22

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG JWT_SECRET_KEY
ARG JWT_EXPIRATION_TIME
ARG JWT_REFRESH_TOKEN_EXPIRATION_TIME
ARG OAUTH2_CLIENT_ID
ARG OAUTH2_CLIENT_SECRET
ARG OAUTH2_REDIRECT_URI
ARG OAUTH2_GRANT_TYPE

# Set environment variables
ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
ENV JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
ENV OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
ENV OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
ENV OAUTH2_REDIRECT_URI=${OAUTH2_REDIRECT_URI}
ENV OAUTH2_GRANT_TYPE=${OAUTH2_GRANT_TYPE}

# Set the working directory
WORKDIR /app

# Copy the Spring Boot jar file to the container
COPY target/tiemcheit-be-0.0.1-SNAPSHOT.jar /app/tiemcheit.jar

# Expose the port the application runs on
EXPOSE 8080

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "tiemcheit.jar"]
